### ISSUE TITLE
Adguard Home shows only one client

### ISSUE THREAD

**Issue by RangerFX4** [mimugmail/opn-repo#10]
Hi,

Thank you for the adguard plugin. Now the problem is Adguard is shows only one client 127.0.0.1 I mapped the port to 3000 and in unbound I put in custom options

```
do-not-query-localhost: no
forward-zone:
name: "."
forward-addr: 127.0.0.1@5353
forward-addr: ::1@5353
```

How can I fix this? so the connected clients will be shown in Adguard.

Regards!

**Comment by mimugmail** [comment]
It would be better to reverse the logic, like listening AGH on 53 LAN and forward to unbound which might listen to localhost only.

**Comment by RangerFX4** [comment]
> It would be better to reverse the logic, like listening AGH on 53 LAN and forward to unbound which might listen to localhost only.

ohh i see. I will try. how can i change the port in AGH?

**Comment by mimugmail** [comment]
Just login to AGH and change it somewhere.
TBH, I dont use it myself, I just saw at the wizard that it can be changed, no idea where this is when running on daily business

**Comment by RangerFX4** [comment]
> Just login to AGH and change it somewhere.
> TBH, I dont use it myself, I just saw at the wizard that it can be changed, no idea where this is when running on daily business

I could not change through the webUI the AGH port but I found out that the settings in opnsense is located 
```
nano /usr/local/AdGuardHome/AdGuardHome.yaml
```
and change the port there. Now everything works as expected thank you!
