### ISSUE TITLE
Tp-Link Omada plugin

### ISSUE THREAD

**Issue by Shurov** [mimugmail/opn-repo#105]
Tp-Link Omada is a business-grade one-glass-solution similar to Ubiquiti UniFi. I must admit, it's less developed for now, but the idea is the same.
There is a [docker container](https://github.com/mbentley/docker-omada-controller) for it, but it'd be good to have it on a hardware firewall.

A bold dream is to have them (OPNsense and Omada Controller) seamlessly integrated - I mean static leases, VLANs, etc, Not sure if it has some API, maybe their CS and developers would like to cooperate

**Comment by mimugmail** [comment]
I already had a look at it some months ago, container runs good, but it's not easily able to adopt to Freebsd.
If there is a port already I can build a plugin

**Comment by Shurov** [comment]
Understood, thanks. closing
