### ISSUE TITLE
Unifi plugin UI improvement

### ISSUE THREAD

**Issue by mihakralj** [mimugmail/opn-repo#11]
Add a link to the Services-Unifi pane that would connect to HTTP://localhost:8443 and launch GUI of Unifi controller

**Comment by mimugmail** [comment]
I'll add a note when the next Controller Release comes out.
Will also add a button to repair mongo db and also logging to UI.

Do you track unifi releases? Then maybe ping me when available. :)

**Comment by mihakralj** [comment]
Yes, I do track Unifi releases and used to run betas on a separate Debian device. Ubiquiti provides the latest builds for Debian but not for BSD. So: where do you (we) source the Unifi controller for BSD? Is the maintainer publishing beta builds too?
