### ISSUE TITLE
os-unboundcustom-maxit not found in repo

### ISSUE THREAD

**Issue by mnaiman** [mimugmail/opn-repo#121]
Hi,

running either OPNsense 22.1 or 22.7.
After install:

```
fetch -o /usr/local/etc/pkg/repos/mimugmail.conf https://www.routerperformance.net/mimugmail.conf
pkg update
pkg search -g -r mimugmail \* | grep bound
```

Result:
```
void-zones-tools-1.0.2_7       Prepare a list of void zones that can be readily fed into Unbound
```

Missing os-unboundcustom-maxit plugin. Via GUI it is same.

**Comment by mimugmail** [comment]
Can you find any other plugins?

**Comment by mnaiman** [comment]
Yes, probably all except custom options for unbound.

On system, where it was installed year ago it is now marked orphaned, but for example Adguard from same repo is ok.

![image](https://user-images.githubusercontent.com/2264442/181620820-9fe7394f-ce1e-4ecf-8288-0f7c68b77700.png)

**Comment by mnaiman** [comment]
This is another box, which I wanted to switch from UFS to ZFS - full reinstall from DVD.
Exported config.xml
Reinstalled, added repo, restored plugins and now it looks like that

![image](https://user-images.githubusercontent.com/2264442/181621185-556e2de9-cb0b-4fc0-ab71-3047b5fe641f.png)

**Comment by mnaiman** [comment]
New created vmware opnsense 22.7, added repo

only unbound custom missing :/

![image](https://user-images.githubusercontent.com/2264442/181622154-7fd14a22-2c99-4338-9495-a13970447c11.png)

**Comment by mnaiman** [comment]
In https://opn-repo.routerperformance.net/repo/FreeBSD:13:amd64/packagesite.txz unbound-custom is not present.
In https://opn-repo.routerperformance.net/repo/FreeBSD:12:amd64/packagesite.txz unbound-custom is present.

Workaround is download https://opn-repo.routerperformance.net/repo/FreeBSD:12:amd64/os-unboundcustom-maxit-1.0.txz
Change in both MANIFEST files to "abi":"FreeBSD:13:amd64","arch":"freebsd:13:x86:64"
Install new package locally via pkg add os-unboundcustom-maxit-1.0.txz 

And plugin is working as expected.

**Comment by mimugmail** [comment]
Need to have a look tonight. I already kicked a build with python39 deps fixed

**Comment by mimugmail** [comment]
Back on track .. please check again :)

**Comment by mnaiman** [comment]
Perfect, problem solved :)
Thanks!
