### ISSUE TITLE
 Expired SSL certificate opn-repo.routerperformance.net 

### ISSUE THREAD

**Issue by kwand** [mimugmail/opn-repo#127]
It seems this repo's SSL certificates have expired again, and I'm unable to do a system update because of this.

Opening the link to the repo in Firefox tells me that it expired today: 
```
Websites prove their identity via certificates, which are valid for a set time period. The certificate for opn-repo.routerperformance.net expired on 2022-08-12.
 
Error code: SEC_ERROR_EXPIRED_CERTIFICATE
```

**Comment by mimugmail** [comment]
I think I fixed this now .. forever .. hopefully :)
