### ISSUE TITLE
alt config for unbound blacklisting service

### ISSUE THREAD

**Issue by mihakralj** [mimugmail/opn-repo#13]
I don't know if the issue will be adopted by the main OPNSense branch, but I really like the proposal from
https://github.com/opnsense/core/issues/4557

Below is my code from _/usr/local/opnsense/scripts/unbound/download_blacklists.py_ with highlighted modification.
I wonder if we could put this alternative configuration of unbound blacklisting that creates 'refuse' blocks instead of 'accept, 0.0.0.0'  into opn-repo?

 ```
   # write out results
    with open("/var/unbound/etc/dnsbl.conf", 'w') as unbound_outf:
        if blacklist_items:
            unbound_outf.write('server:\n')
            for entry in blacklist_items:
               unbound_outf.write("local-zone: \"%s\" refuse\n" % entry)
              # original: unbound_outf.write("local-data: \"%s A 0.0.0.0\"\n" % entry)
```

**Comment by mimugmail** [comment]
There problem here is that the code would be overwritten with the next update.
This repo is only for additions, you really get in trouble when changing the source of core itself.

**Comment by mihakralj** [comment]
Hmmm, then how about this one:
a new widget for the Dashboard that would be configurable with tiles for each service:
 - a tile for ntopng UI, 
 - a tile for Graylog UI, 
 - a tile for Unifi controller UI,
 - a tile for Grafana UI
 ...
Widget would display only active tiles (text and bitmaps)
Tiles could be just a simple local HTML file.

**Comment by mimugmail** [comment]
Better track with separated issues.

**Comment by kadiremrah** [comment]
> 

Hi, I was cruious about how to make dnsbl local-zone inputs with refuse so thank you.
I wanna ask one more thing to make lists smaller. I am blocking TLDs with unbound so I wanna clean the list from the servers with blocked TLDs. Could you comment how can clean the TLDs (like .ga .cc .gq).

Thanks for advance,
