### ISSUE TITLE
os-unifi7-maxit after a couple days 404 error

### ISSUE THREAD

**Issue by norbertjoni** [mimugmail/opn-repo#132]
Hello,

I installed the Unifi plugin and after a couple of days/weeks, I got an HTTP Status 404 – Not Found on:8443 page.

There is any fix for this issue? I don't know when it happened, because I don't usually see the dashboard and there is nothing to do really... My all network is working and I don't have any issues, except I don't access the GUI.

**Comment by mimugmail** [comment]
Did you tr to restart?

**Comment by norbertjoni** [comment]
Just to be clear, for me. 
Should I uninstall the plugin from GUI and delete the folder (/usr/local/share/java/unifi/) 
Or the pkg should remove with the terminal? 

If everything is smooth my app data will be fine? I will back up my opnsene VM for sure. 


Thank you

**Comment by norbertjoni** [comment]
Well, that was not the solution and I have tried to restore my Opnsense VM and looks like the issue it's older than a week.

**Comment by norbertjoni** [comment]
I managed to go back to my Unifi container.
