### ISSUE TITLE
permissions error when trying to install

### ISSUE THREAD

**Issue by mFingers** [mimugmail/opn-repo#139]
When running the `fetch` command, I get the following error:

```
fetch: /usr/local/etc/pkg/repos/mimugmail.conf: open(): Permission denied
```

I am logged in as a user different than `root` (I disabled that user after setting up OPNSense), but the user I am using is in the `admins` group.

I tried using sudo `sudo fetch ...`, but then receive

```
admin is not in the sudoers file.
```

I did try reenabling the `root` user, but I can't log in as that user at all 😕.
Then I tried creating an entirely new user, placing them in the `admins` group, but I get the same "Permission denied" error.

Any pointers would be welcome.  Thanks.

**Comment by mFingers** [comment]
I just did a clean install of the latest version of OPNSense.  Perhaps overkill, but with the importing of an existing config as part of the install, easy enough.

**Comment by wwonka92** [comment]
Hi, running into the exact same issue. Did a fresh re-install of OPNsense virtualized in a Proxmox KVM by importing my config but still not working.
The fetch command always gives me `fetch: https://www.routerperformance.net/mimugmail.conf: Permission denied` even though I'm logged as root.
I really don't understand why can I have permission issues as root !
I tried created a new admin user -> same
checked that I can access the website from inside the VM with `ping www.routerperformance.net` -> OK
I even created manually the file mimugmail.conf but still permission issues when doing the second command for updating the packages.
