### ISSUE TITLE
missing libjxl for ffmpeg/aom

### ISSUE THREAD

**Issue by Gouster4** [mimugmail/opn-repo#144]
Hello. Can you please include libjxl in this repo?
Its required by aom.

Because im not able to get ffmpeg working.

```
# pkg install ffmpeg
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
Updating mimugmail repository catalogue...
mimugmail repository is up to date.
All repositories are up to date.
pkg: aom has a missing dependency: libjxl

```
When i install libjxl with freebsd repos enabled, then i get this error while running ffmpeg:
```
# ffmpeg
ld-elf.so.1: Shared object "libjxl.so.0.8" not found, required by "libaom.so.3"
```

seems like aom version from your repo is incompatible with libjxl in freebsd repo, thats why i would like you to include also libjxl inside your repo. Thanx.

**Comment by mimugmail** [comment]
It will be there in one hour :)
