### ISSUE TITLE
Package request: htop

### ISSUE THREAD

**Issue by cathelijne** [mimugmail/opn-repo#145]
If this is an easy addition for you: could htop be added to the repo? It's a straightforward build from OPNsense ports, and it's so much better than just standard top.

**Comment by mimugmail** [comment]
htop is already in ... `pkg install htop`

**Comment by cathelijne** [comment]
Oh wow, I added it myself from ports. I guess that must have been before I discovered this repo. Sorry for filing a request that's already there 🤦‍♀️
