### ISSUE TITLE
Unifi Controller 7.3.83 Upgrade Request

### ISSUE THREAD

**Issue by ShaunNeutron** [mimugmail/opn-repo#146]
I just found this plugin, but of course my controller is on 7.3.83 and I don't have any backups for 7.3.76 or older. Tried to look through other issues to determine average turn around time, but couldn't find anything. I did find that https://www.freshports.org/net-mgmt/unifi7 has 7.3.83, but I have a feeling that attempting to upgrade from the freebsd repos would break things.

**Comment by mimugmail** [comment]
Its in now ...
