### ISSUE TITLE
OPNsense 23.1.1 Home Assistant Plugin Issue

### ISSUE THREAD

**Issue by Axsgranted** [mimugmail/opn-repo#147]
Didn't start happening until after the upgrade of OPNsense; Errors posted in crash report:

[15-Feb-2023 09:44:12 America/Phoenix] PHP Fatal error:  Uncaught Error: Call to undefined function exec_command() in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code:24
Stack trace:
#0 /usr/local/etc/inc/xmlrpc/hass.inc(12): eval()
#1 /usr/local/opnsense/contrib/IXR/IXR_Library.php(446): exec_php_xmlrpc('\nini_set('displ...')
#2 /usr/local/opnsense/contrib/IXR/IXR_Library.php(384): IXR_Server->call('opnsense.exec_p...', '\nini_set('displ...')
#3 /usr/local/opnsense/contrib/IXR/IXR_Library.php(357): IXR_Server->serve('__construct(Array)
#5 /usr/local/www/xmlrpc.php(104): XMLRPCServer->start()
#6 {main}
  thrown in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code on line 24
[15-Feb-2023 09:45:33 America/Phoenix] PHP Fatal error:  Uncaught Error: Call to undefined function exec_command() in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code:24
Stack trace:
#0 /usr/local/etc/inc/xmlrpc/hass.inc(12): eval()
#1 /usr/local/opnsense/contrib/IXR/IXR_Library.php(446): exec_php_xmlrpc('\nini_set('displ...')
#2 /usr/local/opnsense/contrib/IXR/IXR_Library.php(384): IXR_Server->call('opnsense.exec_p...', '\nini_set('displ...')
#3 /usr/local/opnsense/contrib/IXR/IXR_Library.php(357): IXR_Server->serve('__construct(Array)
#5 /usr/local/www/xmlrpc.php(104): XMLRPCServer->start()
#6 {main}
  thrown in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code on line 24
[15-Feb-2023 09:46:53 America/Phoenix] PHP Fatal error:  Uncaught Error: Call to undefined function exec_command() in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code:24
Stack trace:
#0 /usr/local/etc/inc/xmlrpc/hass.inc(12): eval()
#1 /usr/local/opnsense/contrib/IXR/IXR_Library.php(446): exec_php_xmlrpc('\nini_set('displ...')
#2 /usr/local/opnsense/contrib/IXR/IXR_Library.php(384): IXR_Server->call('opnsense.exec_p...', '\nini_set('displ...')
#3 /usr/local/opnsense/contrib/IXR/IXR_Library.php(357): IXR_Server->serve('__construct(Array)
#5 /usr/local/www/xmlrpc.php(104): XMLRPCServer->start()
#6 {main}
  thrown in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code on line 24
[15-Feb-2023 09:48:15 America/Phoenix] PHP Fatal error:  Uncaught Error: Call to undefined function exec_command() in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code:24
Stack trace:
#0 /usr/local/etc/inc/xmlrpc/hass.inc(12): eval()
#1 /usr/local/opnsense/contrib/IXR/IXR_Library.php(446): exec_php_xmlrpc('\nini_set('displ...')
#2 /usr/local/opnsense/contrib/IXR/IXR_Library.php(384): IXR_Server->call('opnsense.exec_p...', '\nini_set('displ...')
#3 /usr/local/opnsense/contrib/IXR/IXR_Library.php(357): IXR_Server->serve('__construct(Array)
#5 /usr/local/www/xmlrpc.php(104): XMLRPCServer->start()
#6 {main}
  thrown in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code on line 24

**Comment by casualcodr** [comment]
same here since update

**Comment by MaxRei-dev** [comment]
maybee this ist the problem: https://github.com/opnsense/changelog/blob/5ddca563b0852c6cd8bccf195977db68ab1fe490/community/23.1/23.1.1#L24
