### ISSUE TITLE
Can't Use Emoji in SSID on Unifi7

### ISSUE THREAD

**Issue by gbrld** [mimugmail/opn-repo#158]
If I use an emoji in a WiFi network SSID on the UniFi7 plugin, the emoji is replaced with a '?' on the UniFi AP.  This works as expected when using a physical UniFi controller or when using a stand-alone installation of the controller software.

With the UniFi7 plugin, the emoji is stored correctly in the MongoDB (ace.wlanconf), but by the time it reaches the AP (/tmp/system.cfg), it's been replaced by a question mark.  Manually editing the system.cfg and rebooting the AP will get the emoji to display, but it will be eventually replaced by an update from the controller.

**Comment by mimugmail** [comment]
This is not related to the plugin, maybe the freebsd version of Unifi breaks here where I can't help

**Comment by gbrld** [comment]
I've also tested it in a FreeBSD jail on TrueNAS, works as expected there.  Perhaps a dependency versioning issue?
