### ISSUE TITLE
New pkg: Mosquitto

### ISSUE THREAD

**Issue by timota** [mimugmail/opn-repo#16]
Is it possible to add to your repo latest Mosquitto with WebSockets support. 

Thanks

**Comment by mimugmail** [comment]
Does WebSockets require special compile-time options?

**Comment by timota** [comment]
If you will use OpnSense ports - you have to specify 

```
OPTIONS_DEFINE= CARES WS
```
And `yes`, you can compile it from sources - but this requires some `ports` knowledge, which for `end-user` is excessed.
As for me - it will be nice to have such `addon` which can be installed in `one` click. 
Also, for a future, some WebUI can be developed.

**Comment by mimugmail** [comment]
Can you try via:

`pkg update && pkg install mosquitto`

**Comment by timota** [comment]
Sorry for delay. Was busy with other things. 
Looks like PKG doesn't work. It has been compiled without WebSockets

```
mosquitto-1.6.7_1
Name           : mosquitto
Version        : 1.6.7_1
Installed on   : Thu Mar  4 22:06:13 2021 GMT
Origin         : net/mosquitto
Architecture   : FreeBSD:12:amd64
Prefix         : /usr/local
Categories     : net
Licenses       : EPL
Maintainer     : joe@thrallingpenguin.com
WWW            : http://mosquitto.org/
Comment        : Open source MQTT broker
Options        :
	CARES          : on
	PIE            : on
	RELRO          : on
	WS             : off
Shared Libs required:
	libcares.so.2
	libcrypto.so.11
	libssl.so.11
Shared Libs provided:
	libmosquitto.so.1
	libmosquittopp.so.1
Annotations    :
	FreeBSD_version: 1201000
	repo_type      : binary
	repository     : mimugmail
Flat size      : 821KiB
```

if you have compiled with default options - WS not enabled by default. You need to enable it. 

```
OPTIONS_DEFINE= CARES WS
OPTIONS_DEFAULT=        CARES WS
```

Also, is it possible to manage it via configd - i mean to start/stop via WebUI ?

**Comment by mimugmail** [comment]
Can you reinstall the package again and look if it works now?

**Comment by mimugmail** [comment]
ping :)

**Comment by mimugmail** [comment]
Ping :)

**Comment by timota** [comment]
Sorry, didn't test it yet. last one was brought a lot of issues for me. Will try to do it today at the evening and report to you. 

Sorry for inconvenience.

**Comment by mimugmail** [comment]
Happily closing
