### ISSUE TITLE
os-adguardhome-maxit - no autostart on reboot

### ISSUE THREAD

**Issue by Nazgile94** [mimugmail/opn-repo#171]
latest opnsense, adguardhome service doesnt start on opnsense reboot, need to start manually on dashboard.

service -e shows no adguard service.

**Comment by mimugmail** [comment]
Amy errors on the console during reboot?

**Comment by Nazgile94** [comment]
Nope, filtered "adguard" nothing

**Comment by Nazgile94** [comment]
Nope, non Error in Boot on Monitor , need to manually start adguard over the gui Dashboard 

Maybe i can fix this with a @start cron ?
Just need to know the Argument

**Comment by PerLycke** [comment]
Same here. All other services auto starts except adguard, and I have to start it manually after every reboot. No errors shown

**Comment by mimugmail** [comment]
Also when attaching a Display and watching bootup?

**Comment by karelkryda** [comment]
Can confirm this behaviour. I have to manually start the AdGuard Home plugin from the OPNsense interface. Also, the restart service button does not work for me. When I press the "Restart Service" button, the service turns off and I have to use the button to turn it back on.
If AdGuard Home is the main DNS server on the network, this causes serious problems.

**Comment by Nazgile94** [comment]
Exactly the Same, restart = Service Turns Off, need To manually start it.

**Comment by mimugmail** [comment]
Fixed in latest 1.12 :)

**Comment by efaden** [comment]
Sorry to bring up an old topic, I am running 1.15.  I have tried uninstalling, reinstalling, etc.... still no autostart.  There are no errors in the log.  Manually starting, restarting, stopping all seem to work fine.  Also I see no service listed in service -e.... any suggestions where to go from here?

Unable i have even run service adguardhome enable/disable etc.... it is correctly modifying the rc.conf.d folder... but I still never see it show up in service -e
