### ISSUE TITLE
Adguardhome set as primary DNS breaks BIND

### ISSUE THREAD

**Issue by SimonFischer04** [mimugmail/opn-repo#172]
Hi,
When you set AdguardHome as primary DNS this breaks the BIND plugin with the following error: 
```
/usr/local/opnsense/mvc/app/models/OPNsense/Bind/General.php:50: in_array(): Argument #2 ($haystack) must be of type array, int given
```

---
Steps to reproduce:
- install AdguardHome plugin
- install os-bind plugin
- enable adguardhome and check the "Primary DNS" setting.
- try to start BIND by checking "Enable BIND Daemon"
- => get the ERROR described above
---

PS: what does this "Primary DNS" setting in adguardHome actually do? Maybe a little more description would be welcome than just "Enable if AdGuardHome runs on port 53."

**Comment by SimonFischer04** [comment]
53530

**Comment by SimonFischer04** [comment]
may can look into this myself, but unfortunately can't find the source for the adguard plugin in this repo. am i missing something?

**Comment by mimugmail** [comment]
Did you try latent 1.10? It fixed a bug with ports

**Comment by SimonFischer04** [comment]
currently working on updating to 23.7 as this seems to be required.
Still, just curious, why the source isn't here but others like custom unbound / nextdns are.

**Comment by SimonFischer04** [comment]
seems to be fixed now, great 👍.

PS: a little more info on the changelog than "Fix inc which leads to errors after 23.7" or access to source would have been great.

**Comment by mimugmail** [comment]
> currently working on updating to 23.7 as this seems to be required. Still, just curious, why the source isn't here but others like custom unbound / nextdns are.

Because lazy .. source is in /usr/local/opnsense when installed like every other plugin

**Comment by SimonFischer04** [comment]
> > currently working on updating to 23.7 as this seems to be required. Still, just curious, why the source isn't here but others like custom unbound / nextdns are.
> 
> Because lazy .. source is in /usr/local/opnsense when installed like every other plugin

adding to github would allow community contributions, but ok - understanable. everyone is lazy (sometimes) :smile: 
thanks for fixing anyway
