### ISSUE TITLE
UniFi Controller 7.4.162

### ISSUE THREAD

**Issue by Sk4y** [mimugmail/opn-repo#174]
Hey are there any plans to update the unifi package to the latest release ([7.4.162](https://community.ui.com/releases/UniFi-Network-Application-7-4-162/50b4b930-631e-4ada-87c4-0b4ea5fb26a7))? There have been a few releases of the 7.4.x series in the last months, but haven't seen any updates to the opn-repo.

**Comment by mimugmail** [comment]
Can you do a backup and change in mimugmail.conf /repo/ to /transfer/ ? Its beta and I need testers

**Comment by Sk4y** [comment]
Will do that.

**Comment by Sk4y** [comment]
@mimugmail Any updates on this?

**Comment by DrDrache** [comment]
so I attempted this migration- and it was a bit more involved than just changing the repo - this is how I got it running :

1. make a backup and download to local machine
2 . UNINSTALL (remove) os-unifi7-maxi (this will also remove many depends)
3 . Manually clean the plugin directory :

```
root@OPNSENSE:/var/run # cd /usr/local/share/java/
root@OPNSENSE:/usr/local/share/java # rm -rf ./unifi/
```

4. reinstall os-unifi7-maxi
5. follow initial setup (port 8080) - restoring backup from Local machine
6. wait for 5-8 minutes (I didn't actually time it) for the service to shut down (or manually force it down after 10)
7. restart service, and log into your restored configuration

![image](https://github.com/mimugmail/opn-repo/assets/774182/0176df6a-159c-4587-bab1-bd551d5e52cd)

**Comment by Sk4y** [comment]
> so I attempted this migration- and it was a bit more involved than just changing the repo - this is how I got it running :
> 
>     make a backup and download to local machine
>     edit /usr/local/etc/pkg/repos/mimugmail.conf (change /repo to /transfer)
>     UNINSTALL (remove) os-unifi7-maxi (this will also remove many depends)
> 
> 4 . Manually clean the plugin directory :
> 
> root@OPNSENSE:/var/run # cd /usr/local/share/java/
> root@OPNSENSE:/usr/local/share/java # rm -rf ./unifi/
> 
>     reinstall os-unifi7-maxi
>     follow initial setup (port 8080) - restoring backup from Local machine
>     wait for 5-8 minutes (I didn't actually time it) for the service to shut down (or manually force it down after 10)
>     restart service, and log into your restored configuration

Did this before also the cleanup. Tried it 30min ago but isnt still working. Still get this Error "HTTP Status 404 – Not Found".

**Comment by DrDrache** [comment]
> > so I attempted this migration- and it was a bit more involved than just changing the repo - this is how I got it running :
> > ```
> > make a backup and download to local machine
> > edit /usr/local/etc/pkg/repos/mimugmail.conf (change /repo to /transfer)
> > UNINSTALL (remove) os-unifi7-maxi (this will also remove many depends)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 4 . Manually clean the plugin directory :
> > root@OPNSENSE:/var/run # cd /usr/local/share/java/
> > root@OPNSENSE:/usr/local/share/java # rm -rf ./unifi/
> > ```
> > reinstall os-unifi7-maxi
> > follow initial setup (port 8080) - restoring backup from Local machine
> > wait for 5-8 minutes (I didn't actually time it) for the service to shut down (or manually force it down after 10)
> > restart service, and log into your restored configuration
> > ```
> 
> Did this before also the cleanup. Tried it 30min ago but isnt still working. Still get this Error "HTTP Status 404 – Not Found".

all i can say - is that I did have to restart the service a few times - I figured i wasn't waiting long enough.
the only thing that "gets rid" of the 404 (had it with a previous upgrade as well) is cleaning the directories after an uninstall, and just "waiting longer" for the service to come up.
