### ISSUE TITLE
Traefik, Caddy, Adguard, etc. installation files? 

### ISSUE THREAD

**Issue by mietzen** [mimugmail/opn-repo#178]
Hi,

I'm very new to OPNsense / FreeBSD and I'm not fully aware of how `pkg` repositories work. 

Normally before I install any 3rd party packages I like to get a overview of the source code and make sure I roughly understand what is going to happen. On your Homepage you list, e.g.: 

- ...
- AdGuardHome (os-adguardhome-maxit) / it listens on 3000, sadly same as ntopng and Grafana
- Speedtest (os-speedtest-community) by mihak09
- Traefik (os-traefik-maxit)
- Caddy (os-caddy-maxit)
- ...

I found the installation files for Speedtest: https://github.com/mimugmail/opn-repo/tree/main/net-mgmt/speedtest-community
But not for Traefik, Caddy and Adguard. Are these closed source? 

Please don't understand this as some kind of accusation, I'm just curious how stuff works.

**Comment by mimugmail** [comment]
Hi, 

no its not closed, but my git and build arch is internal and via github there are plugins not build by me. I always need to sync them down, so this would double the work when publishing them there but not using it. You can download the pkgs and extract them, its like zip and you see all files and folders :)

**Comment by mietzen** [comment]
For anybody that comes after me:

- Download packagesite.txz: https://opn-repo.routerperformance.net/repo/FreeBSD:13:amd64/packagesite.txz
FreeBSD:13:amd64 is my ABI, this might change in the future, you can find out yours via `pkg config abi`
- Extract it `tar -xf packagesite.txz`, read `packagesite.yaml` find the package you are interested in, e.g. `caddy-2.6.4_1.pkg`
- Download it under e.g.: https://opn-repo.routerperformance.net/repo/FreeBSD:13:amd64/caddy-2.6.4_1.pkg
- Extract it `tar -xf caddy-2.6.4_1.pkg` 
- Profit 😄

**Comment by mimugmail** [comment]
Thx :)
