### ISSUE TITLE
OPNsense fetch command not working (certificate error)

### ISSUE THREAD

**Issue by r-jansen** [mimugmail/opn-repo#183]
Hi,

When I try to run the command in SSH on my OPNsense (firmware 23.7.6):
fetch -o /usr/local/etc/pkg/repos/mimugmail.conf https://www.routerperformance.net/mimugmail.conf

I get an error:
Certificate verification failed for /C=DE/CN=routerperformance.net/emailAddress=webmaster@routerperformance.net
28483183874048:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1921:
fetch: https://www.routerperformance.net/mimugmail.conf: Authentication error

I also get a certificate error if I go to the website routerperformance.net.

Could you please fix the certificate, thank you very much!

Or am I doing something wrong?

Kind regards,
Raymond

**Comment by mimugmail** [comment]
Should be ok now?

**Comment by r-jansen** [comment]
Yes, it's working now. Thanks!

**Comment by r-jansen** [comment]
Yes, it works now. Thanks!
