### ISSUE TITLE
Zeek plugin error at installation

### ISSUE THREAD

**Issue by thelittlefireman** [mimugmail/opn-repo#19]
Hi,
When i try to install os-zeek-maxit-plugin on my opnsense 21.1.3 i've got this following error :

```
Using existing user 'zeek'.
[3/4] Extracting zeek-3.0.12_2: .......... done
Error: running "zeek -v" failed with output:
ld-elf.so.1: Shared object "libssl.so.11" not found, required by "zeek"
```

My opnsense is configure for using libressl (vs openssl) i don't know if it's related.

Thanks
Thomas

**Comment by thelittlefireman** [comment]
For information i've try to change to `openssl` and it's working. Could it be possible to fix it for `libressl` ?

**Comment by mimugmail** [comment]
Sorry, but I dont build against libressl, it's way too much effort for this little project:
https://www.routerperformance.net/opnsense-repo/

**Comment by thelittlefireman** [comment]
No pb ;)
