### ISSUE TITLE
Assign vLAN for Unifi Plug-in

### ISSUE THREAD

**Issue by Mark-Hicks** [mimugmail/opn-repo#201]
I am wondering if there is a way to bind the unifi plug-in to a vLAN interface? This would be very helpful as all my WAPs are managed on a separate vLAN and, given how the firewall is positioned in the network, running the Unifi controller on the LAN interface is not ideal for my use case.

**Comment by mimugmail** [comment]
The controller will listen on All interfaces per default and you can manage access via Firewall rules

**Comment by Mark-Hicks** [comment]
Excellent. Thank you for the quick response. Having already restored a backup from my Cloud Key, I assume I just need to assign the former IP of the Cloud Key to a vLAN interface on OpnSense, restart, and the WAPs should connect to the new controller then?

-/\/\ark

On Feb 19, 2024, at 12:53 AM, Michael ***@***.***> wrote:

﻿

The controller will listen on All interfaces per default and you can manage access via Firewall rules
