### ISSUE TITLE
ocserv missing after upgrade Opnsense to 23.7.12

### ISSUE THREAD

**Issue by nikolaysu** [mimugmail/opn-repo#203]
root@fw1:/usr/local/etc/pkg/repos # pkg install ocserv
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
Updating mimugmail repository catalogue...
mimugmail repository is up to date.
All repositories are up to date.
pkg: libevent has a missing dependency: openssl
pkg: xmlsec1 has a missing dependency: openssl

I think this is the same problem as here? https://github.com/mimugmail/opn-repo/issues/199

**Comment by mimugmail** [comment]
It only works with 24.1

**Comment by nikolaysu** [comment]
Thank you!

It really works. 

And thanks also for your work on the repository.

**Comment by fgor09** [comment]
Where can I see an example of configuring the OCServ ?

**Comment by mimugmail** [comment]
Only official docs, I dont use it myself

**Comment by fgor09** [comment]
But you have created a plugin and the GUI has certificate settings and a field for settings. What should I enter in this field? This field is for the OCServ main configuration file, so the certificate settings are indicated there - and you have a choice of certificates in the plugin. Then where can I set up users for OCServ?
It feels like you created this plugin just for show :( 
At least for me it is not clear how to configure this plugin :(

**Comment by mimugmail** [comment]
No, I build it in my spare time, for free, for everyone. Its for users experienced with ocserv (e.g. already running am instance on linux).

**Comment by fgor09** [comment]
Thank you so much for that. But it is still unclear how to use this plugin.
It's easier for me to raise OCServ separately and just set up NAT on OPNsense.
