### ISSUE TITLE
nTop-ng No Vulnerability Scan Type

### ISSUE THREAD

**Issue by n0w33d** [mimugmail/opn-repo#213]
Host OS: FreeBSD 13.2-RELEASE-p10
Host distribution: OPNsense 24.1.4-amd64
ntop version: ntopng Community v.6.0.240320 rev.0 (FreeBSD 13.2)

Issue: For ntop-ng on version 1.3 (the actual ntop version is v6) there is no option for Vulnerability scan in the menu. When navigating to the Vulnerability Scan module within ntop, the option for any scan types are missing.

~~Even after installing nmap manually along with vulscan I cannot get the ntop-ng GUI to give me anything no matter if nmap and vulscan are installed or not.~~

![image](https://github.com/ntop/ntopng/assets/106119998/123e3760-3489-414e-b50e-7f76db7bd919)

![image](https://github.com/ntop/ntopng/assets/106119998/c88f304f-6c3a-426e-9535-3d52ccb247e0)

![image](https://github.com/ntop/ntopng/assets/106119998/070100f4-94e5-4bbc-bcb9-b80784df8c9f)

This may be a repository issue. Please refer to the issue replies by ntop developers here:
https://github.com/ntop/ntopng/issues/7981#issuecomment-2032075053

**Comment by mimugmail** [comment]
Why is this related to my repo? :)

**Comment by ayeifry** [comment]
Any solution on this issue?
