### ISSUE TITLE
Problems updating the mimugmail repo OPNsense

### ISSUE THREAD

**Issue by 69leo** [mimugmail/opn-repo#218]
Hi, I'm having problems updating the mimugmail repo:

Updating OPNsense repository catalogue...
OPNsense repository is up to date.
Updating mimugmail repository catalogue...
pkg-static: https://opn-repo.routerperformance.net/repo/FreeBSD:13:amd64/meta.txz: Authentication error
repository mimugmail has no meta file, using default settings
pkg-static: https://opn-repo.routerperformance.net/repo/FreeBSD:13:amd64/packagesite.pkg: Authentication error
pkg-static: https://opn-repo.routerperformance.net/repo/FreeBSD:13:amd64/packagesite.txz: Authentication error
Unable to update repository mimugmail
Error updating repositories!
Starting web GUI...done.
Generating RRD graphs...done.

*** OPNsense.my: OPNsense 24.1.7 ***

root@OPNsense:~ # curl -vI https://opn-repo.routerperformance.net/repo/FreeBSD:13:amd64/packagesite.txz
* Host opn-repo.routerperformance.net:443 was resolved.
* IPv6: (none)
* IPv4: 46.16.78.247
*   Trying 46.16.78.247:443...
* Connected to opn-repo.routerperformance.net (46.16.78.247) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to opn-repo.routerperformance.net:443
* Closing connection
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to opn-repo.routerperformance.net:443

Please help me solve this

**Comment by svendt** [comment]
Any solution here, I have the same error?

**Comment by 69leo** [comment]
I'm still waiting for a solution to this problem. It doesn't seem to depend on the business or free version, the error is everywhere

**Comment by mimugmail** [comment]
fixed now
