### ISSUE TITLE
Unifi Controller 6.1.71

### ISSUE THREAD

**Issue by brenix** [mimugmail/opn-repo#22]
Are there plans to update the unifi package to the latest release ([6.1.71](https://community.ui.com/releases/UniFi-Network-Controller-6-1-71/0cffd3ed-7429-4529-9a20-9fead78ebf66))? It looks like there have been a few releases of the 6.1.x series in the last month, but haven't seen any updates to the opn-repo.

**Comment by mimugmail** [comment]
Would you like to beta-test? :)

**Comment by brenix** [comment]
Wouldn't mind giving it a go! Is it still in beta, or was that sarcasm (I might have read it was still beta somewhere)?  I'm just not very familiar with the package manager or how the packages are generated in freebsd.

**Comment by mimugmail** [comment]
Eh, no, but I don't have a running setup here. I build the binary but I can't test if upgrade will run fine.
If you have a backup then SSH into you OPN and edit the file: /usr/local/etc/pkg/repos/mimugmail.conf

Replace "repo" in the link with "transfer".

Then "pkg update && pkg upgrade" and it will upgrade to latest version

**Comment by brenix** [comment]
Will give it a shot tomorrow and report back. Thanks!

**Comment by brenix** [comment]
Upgrade was smooth for me as well. I had to trigger a restart of the unifi service after the upgrade to ensure the controller was running the correct version.

**Comment by brenix** [comment]
Going to close this since it looks like it works for folks and and is now available.. Thanks!
