### ISSUE TITLE
Adding repo install package to OPNsense plugins 

### ISSUE THREAD

**Issue by mihakralj** [mimugmail/opn-repo#23]
I was perusing the source code of various plugins and stumbled upon package that adds SunnyValey repo to OPNsense and therefore enables Sensei.

Any thoughts on replicating the same model to enable opn-repo?

And the same model to install ports, which are not included in OPNsense by default?

**Comment by mimugmail** [comment]
No, SunnyValley is a Partner and they have an agreement to be there. The plugins here also have to many limitations
