### ISSUE TITLE
Business version - ssl problems with repo

### ISSUE THREAD

**Issue by JuSchi89** [mimugmail/opn-repo#232]
Hello,
I want to draw attention on the OPNsense business version. Since a few updates ssl errors occur when updating.
Few months ago was said that this is because of opnssl3 and would be fixed automatically when version 24.4 would be released. This wasn't the case. And now I updated to the latest 24.4.2 and it still doesn't work.

When will this be fixed?
Best regards!

**Comment by mimugmail** [comment]
Fixed now
