### ISSUE TITLE
OPN-Arp: contribution

### ISSUE THREAD

**Issue by mr-manuel** [mimugmail/opn-repo#238]
Hello,

thanks for initializing this great plugin. I spend some hours to extend the plugin a bit. Are you interested in adopting the modifications? If yes, where should I upload the files? Unfortunately the [opn-arp](https://github.com/mimugmail/opn-arp) repository is still a bit empty.

![opn-arp](https://github.com/user-attachments/assets/aa9784de-943c-477a-8a7e-20d4ce3f46d7)

**Comment by mr-manuel** [comment]
Perfect, thanks. I will open a PR, once I tested it for a few days.

**Comment by mr-manuel** [comment]
I now rewrote the whole plugin and nearly no original code is left. So my question is now, if it's better to create my own repository or if you can add my GitHub name and link to this plugin?

**Comment by mimugmail** [comment]
Sure, just create a new one and call it -community instead of -maxit

**Comment by mimugmail** [comment]
I didn't have a look at it yet, but since I have no merge rights over there I can't do much :)

**Comment by mr-manuel** [comment]
No merge rights needed in this case :-) I have some questions/issues, maybe you know an answer to that or have a path you can lead me.
