### ISSUE TITLE
Enhancements of Unifi plugin

### ISSUE THREAD

**Issue by mihakralj** [mimugmail/opn-repo#24]
I wrote a bit of php code to display relevant details that are pulled via API calls from unifi controller. It can display info on the (enhanced) Volt page of Unifi, but I could make a widget to display core Unifi vitals (heath, num of clients, alerts) on thr dashboard.

Any interest? How do I pass the kludge of my quasi-coding over? 😊

**Comment by mimugmail** [comment]
I will add the source to the repo so you can  PR against. Also regarding speedtest plugin if you like.

**Comment by mihakralj** [comment]
Oh man, speedtest plugin with mutually-exclusive dependencies on either Ookla binary or ports-based python test is a nightmare to solve! They both take over the name "speedtest" in /usr/local/bin and i would really really like to bring them both in somehow...

(results with Ookla binary are consistently better than results from ports)

**Comment by mimugmail** [comment]
Did you reach out for the Ookla guys about releasing the source so we can manage a port?

**Comment by mihakralj** [comment]
I did - with no response. We will need to treat it just like other closed-source packages, with additional nuisance that it steamrolls over the open-source port of speedtest...

**Comment by mimugmail** [comment]
You can add the unifi PR here: https://github.com/mimugmail/opn-repo/tree/main/net-mgmt/unifi-maxit

**Comment by mihakralj** [comment]
OK, but first I need to un-hard-code the unify credentials out from my PHP code. Any suggestions? I am thinking to add two fields to a Volt template and model (username and password) and store them in conf/config.xml.

I am using PHP wrapper for Unifi API from here: https://github.com/Art-of-WiFi/UniFi-API-client

**Comment by mihakralj** [comment]
I forked this repo and - for a start - created a branch for speedtest plugin, as it is more fleshed out and ready for testing.
It is ready for a Pull Request whenever you agree.

**Comment by mimugmail** [comment]
> I forked this repo and - for a start - created a branch for speedtest plugin, as it is more fleshed out and ready for testing.
> It is ready for a Pull Request whenever you agree.

Sure :)

**Comment by mimugmail** [comment]
> OK, but first I need to un-hard-code the unify credentials out from my PHP code. Any suggestions? I am thinking to add two fields to a Volt template and model (username and password) and store them in conf/config.xml.
> 
> I am using PHP wrapper for Unifi API from here: https://github.com/Art-of-WiFi/UniFi-API-client

This is ok for me, but please add those in a new tab and make it optional so anyone can run it like before.
Current version is 6.1 which may not be supported by API client?

**Comment by mihakralj** [comment]
[Unifi.zip](https://github.com/mimugmail/opn-repo/files/6283481/Unifi.zip)

A prototype to test and discuss how to proceed. In the archive is:
- modified GeneralController that is adding three more endpoints (status, clients, devices)
- modified models/menu.xml that is adding the same three pages under Unifi node (and I added VisibleName to be "Unifi Controller")
- three new VOLT pages (status, clients, devices)
- a Client.php code (from https://github.com/Art-of-WiFi/)
- and THE MOST IMPORTANT: config.php <= you need to add credentials and IP address of unifi in here

Status page is bearable and I could parse it with no problem
Devices and Clients page... Oh my. There is SO MUCH information coming back from Unifi controller, we need a plan what to parse and what to ignore.

**Comment by mihakralj** [comment]
![image](https://user-images.githubusercontent.com/31756078/114137532-3332a800-98c1-11eb-9137-a6ac9ca481c2.png)

**Comment by mimugmail** [comment]
Can you please fork the repo and make a PR against it? It think it would be better to template the .php file via volt so you can enter the credentials via UI :)

**Comment by mihakralj** [comment]
I am so far from being ready to issue a pull request... There is nothing yet in the plugin and I don't want to do regular PRs into a stable repo with junk code. Heck, this prototype is not even ready to be in my own repo yet! I just wanted to show you how much data comes back from Unifi...

Give me a week or two and I'll have something to submit and show.

**Comment by mihakralj** [comment]
Some progress and an update:
- I finally managed to wrangle the right combination of storing Unifi credentials in conf/config.xml, reading them in PHP and using Art-of-Wifi PHP library to show/act on the data (see screenshot below)
- the PHP calls don't refresh (doh!) so I am going to move PHP calls to Unifi out from Volt pages into the Controller/API.
- Essentially, I first need to create an OPNSense API wrapper for all Art-of-Wifi calls (with credentials captured and stored in conf/config.xml), and then start building (auto-refreshing) Volt pages and Widgets.
- Good news: I can make this for OPNSense without the need to actually run Unifi controller on OPNSense! This can become a (simple and limited) integrated UI to manage any Unifi on the network.
![image](https://user-images.githubusercontent.com/31756078/115279566-bf33a380-a0fb-11eb-91df-11d02fc56b44.png)

**Comment by mimugmail** [comment]
Wow, really nice progress :)

**Comment by mihakralj** [comment]
OK, I am stuck in the weeds of PHP, trying to marry an Unifi_API class (in its own namespace) with the PHP black magic that drives API controller in OPNSense. (it doesn't help that I am a complete rookie in PHP and Phalcon). I can EITHER make an API controller that reads data from config.xml (using OPNsense\Core\Config) OR make a functional call to Unifi API - but not both.

Before I descend into the madness of deciphering OPNsense PHP classes, who is the person that I could nag with PHP/Phalcon questions?

**Comment by mihakralj** [comment]
Small but joyful progress:

![image](https://user-images.githubusercontent.com/31756078/116841430-09059a80-ab8e-11eb-8050-6f4db6511c3a.png)

**Comment by mihakralj** [comment]
Let me close this issue and re-open a new one..
