### ISSUE TITLE
Unbound logs swamped with DNS queries for opn-repo.routerperformance.net

### ISSUE THREAD

**Issue by V4ler1an** [mimugmail/opn-repo#244]
I've just noticed that my OPNsense Unbound DNS logs are getting flooded with queries for these two domains, at the same time, every 30 seconds. There are approx 25 on the A and 25 on the AAAA records of both domains:

opn-repo.routerperformance.net
pkg.opnsense.org

Together they amount to 67% of all DNS lookups, dwarfing everything else. What's going on here? How is this necessary? Is it telemetry related? I run two plugins that are sourced from the opn-repo:

AdGuard Home (os-adguardhome-maxit)
Home Assistant (os-homeassistant-maxit)

Is this a bug perhaps? Is anyone else seeing the same? Appreciate your feedback / assistance.

**Comment by mimugmail** [comment]
Maybe a hanging update process? You only trigger such requests when checking for updates. No telemetry on my side .. for what reason? :)

**Comment by V4ler1an** [comment]
Thanks. I've since discovered that the requests match the 'scan interval' setting in the Home Assistant OPNsense integration that talks to the os-homeassistant-maxit plugin. I'll raise an issue on their GitHub.

**Comment by SiLenCe-WB** [comment]
> Thanks. I've since discovered that the requests match the 'scan interval' setting in the Home Assistant OPNsense integration that talks to the os-homeassistant-maxit plugin. I'll raise an issue on their GitHub.

Did you find out a way to stop queries to both opn-repo.routerperformance.net and pkg.opnsense.org? As soon as I enable any sensor on the hass-opnsense integration, I get 6 queries to those DNS every 30 seconds.

**Comment by V4ler1an** [comment]
No mine stopped but I did log it and thought Snuffy [fixed it](https://github.com/travisghansen/hass-opnsense/issues/322). If it's returned it hasn't for me yet.

**Comment by engels0n** [comment]
Bug is back since 2026.4.1, hoping for a fix.

<img width="627" height="1002" alt="Image" src="https://github.com/user-attachments/assets/4f4dcfc5-a6ad-444e-a661-fee5da37bcec" />

**Comment by V4ler1an** [comment]
Might be worth raising it [here](https://github.com/travisghansen/hass-opnsense).
