### ISSUE TITLE
Fix UTF-8 Wi-Fi names in Unifi Network Application

### ISSUE THREAD

**Issue by lilyinstarlight** [mimugmail/opn-repo#250]
Wi-Fi SSIDs seemingly get automatically ASCII-fied (at least emoji are transliterated into `?`) unless `-Dfile.encoding=utf8` is specified in `unifi_javaflags` (which is in the flags set by the upstream UniFi init file)

Please update the default rc value for `unifi_javaflags` to the following in `/usr/local/etc/rc.d/unifi`, thank you!

```sh
: ${unifi_javaflags="-Djava.awt.headless=true -Xmx1024M \
	-Dfile.encoding=UTF-8 \
	-Djava.net.preferIPv4Stack=false \
	--add-opens java.base/java.lang=ALL-UNNAMED \
	--add-opens java.base/java.time=ALL-UNNAMED \
	--add-opens java.base/sun.security.util=ALL-UNNAMED \
	--add-opens java.base/java.io=ALL-UNNAMED \
	--add-opens java.rmi/sun.rmi.transport=ALL-UNNAMED"}
```

**Comment by mimugmail** [comment]
You need to file a bug in freebsd ports, not here. I dont touch those files

**Comment by lilyinstarlight** [comment]
Ah yep, I see it here: <https://cgit.freebsd.org/ports/tree/net-mgmt/unifi8/files/unifi.in> (I wasn't aware you were using upstream port)

I'll submit something upstream then, thank you!

**Comment by lilyinstarlight** [comment]
I've opened <https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=283443> now, thanks again!
