### ISSUE TITLE
CrowdSec

### ISSUE THREAD

**Issue by b4b857f6ee** [mimugmail/opn-repo#4]
Hello,

Once we got the FreeBSD version.
https://crowdsec.net/

It's not yet on FreeBSD but just to remember it and don't forget it once they have it on the distro 👍

**Comment by mimugmail** [comment]
It's now in community repo:

`pkg install crowdsec
`
If you tell me something about config and syntax I can try to build a plugin

**Comment by b4b857f6ee** [comment]
SO GOOOOOD!!!!!!

**Comment by twarnick** [comment]
hi, the version here is 1.1.1 and is not usable anymore. 
`WARN[15-12-2021 10:03:36 PM] Crowdsec is not the latest version. Current version is 'v1.1.1' and the latest stable version is 'v1.2.1'. Please update it! 
`

**Comment by mimugmail** [comment]
Sorry but the port in FreeBSD is outdated, maybe ping the port maintainer?
