### ISSUE TITLE
AdGuardHome installation failed

### ISSUE THREAD

**Issue by Gogolathome** [mimugmail/opn-repo#5]
I installed your OPNsense repository and tried to install AdGuardHome.
The plugin is installed but the package apparently not. It is missing, although I can see it in the packages list on OPNsense.
I really don't know what went wrong, but I fetched the FreeBSD 64bit package from Adguard, extracted it and copied the binary to /usr/local/opnsense/service/ directory.
Then I was able to login on port 3000 and it is working fine now. I disabled Unbound/dnscrypt-proxy because AdGuardHome has the same/more functionality and a nice interface.
Thanks for your repository. I hope you can find the problem with installation.

**Comment by mimugmail** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/2536#issuecomment-758546903

I'm already working on it. Will release a new plugin when finished

**Comment by bumasl** [comment]
the panel with port 3000 does not open, any additional configuration?

**Comment by mimugmail** [comment]
It doesnt even start .. I'll rework the while package

**Comment by bumasl** [comment]
in service status if active

**Comment by Gogolathome** [comment]
> 
> 
> [AdguardTeam/AdGuardHome#2536 (comment)](https://github.com/AdguardTeam/AdGuardHome/issues/2536#issuecomment-758546903)
> 
> I'm already working on it. Will release a new plugin when finished

Ok, I have read that. So now I see AdGuardHome is installed in /usr/local/AdGuardHome. Why is the file /usr/local/etc/rc.d/AdGuardHome pointing to /usr/local/opnsense/service/AdGuardHome? Because I moved the binary "AdGuardHome" to this location it is working fine now!
Only problem is it doesn't run on boot and because I disabled Unbound/dnscrypt-proxy combination I had to put my interface ipv4/ipv6 addresses in DHCP server DNS. Leaving it blank didn't work anymore, so that is an OPNsense thing I guess.

**Comment by Gogolathome** [comment]
> 
> 
> [AdguardTeam/AdGuardHome#2536 (comment)](https://github.com/AdguardTeam/AdGuardHome/issues/2536#issuecomment-758546903)
> 
> I'm already working on it. Will release a new plugin when finished

Ok, I have read that. So now I see AdGuardHome is installed in /usr/local/AdGuardHome. Why is the file /usr/local/etc/rc.d/AdGuardHome pointing to /usr/local/opnsense/service/AdGuardHome? Because I moved the binary "AdGuardHome" to this location it is working fine now!
Only problem is it doesn't run on boot and because I disabled Unbound/dnscrypt-proxy combination I had to put my interface ipv4/ipv6 addresses in DHCP server DNS. Leaving it blank didn't work anymore, so that is an OPNsense thing I guess.

**Comment by mimugmail** [comment]
I finally got AdGuardHome working as an @opnsense plugin. Grab it from here: https://www.routerperformance.net/opnsense-repo/

It's still lacking status view, but after install and enabling it's available via port 3000 (if no other service listens to it). 

If you had a previous version better remove it via CLI (pkg and plugin), but then also config is wiped.

**Comment by Gogolathome** [comment]
Thank you. I copied my settings and data file to the new location. All good!
