### ISSUE TITLE
Adguard Updates - Able to use built in updater?

### ISSUE THREAD

**Issue by smbm** [mimugmail/opn-repo#60]
I have done a search for forum and Reddit posts but not found anything specific about whether it is safe to use the built in Adguard updater for the Adguard plugin.

I am in the process of migrating to OPNsense and have everything pretty much setup now. Adguard is giving a banner message at the top prompting to update but as a new user I am not sure whether this will cause issues or update fine.

Can you advise whether this has been tested or not at all?

Thanks very much for all your work, it has made replacing my Unifi stack and PiHole an easy task.

**Comment by mimugmail** [comment]
Inline-Update works fine. I usually update the plugin with every major update like 0.106 to 0.107

**Comment by smbm** [comment]
Amazing thanks, and thanks again for all your work.

**Comment by smbm** [comment]
Just ran the update, it worked perfectly. Will mark this closed.
