### ISSUE TITLE
Icons not loading in some pages when using Solarized/Dracula

### ISSUE THREAD

**Issue by rpoovey** [mimugmail/opn-repo#61]
I have noticed some icons are not loading properly in both Solarized and Dracula themes. Tested in both Firefox and Safari. Screen shots from the "Interfaces - Assignments" menu.

<img width="110" alt="Screen Shot 2021-06-01 at 8 31 18 AM" src="https://user-images.githubusercontent.com/5035579/120324010-1f4d6600-c2b4-11eb-9c84-89398b5bc8cf.png">
<img width="125" alt="Screen Shot 2021-06-01 at 8 31 34 AM" src="https://user-images.githubusercontent.com/5035579/120324012-1fe5fc80-c2b4-11eb-9ca3-66e357113b94.png">

**Comment by mihakralj** [comment]
Good catch! That plug icon is sourced from a Glyphicon library while the theme uses Fontawesome icon library.
Can you try and add this to your `main.css` - the plug icon should now be resolved:
```
.glyphicon.fa.fa-plug::before {
  content:"\f1e6";
  font-family:"Font Awesome 6 Pro";
}
```
If that works, I'll add the change to the next update of Solarized theme.

**Comment by rpoovey** [comment]
`.glyphicon.fa-plug::before {
  content:"\f1e6";
  font-family:"Font Awesome 6 Pro";
}
`
Had one too many ".fa" in there, once edited it is displaying properly in Dracula theme.

**Comment by rpoovey** [comment]
Looks like "Firewall - Rules - Interface" has some too. Screenshot from the bottom of the rules page. Dracula appears to be worse than Solarized.

Looking at `all.min.css` in the Dracula folder I have indented the code, looks like line `7346` is the icon its sourcing. 

<img width="192" alt="Screen Shot 2021-06-01 at 2 34 37 PM" src="https://user-images.githubusercontent.com/5035579/120373566-8126c380-c2e6-11eb-9b91-2aa8cc9a8cd7.png">

<img width="153" alt="Screen Shot 2021-06-01 at 2 32 41 PM" src="https://user-images.githubusercontent.com/5035579/120373441-5b99ba00-c2e6-11eb-94e9-10f573be48c0.png">

**Comment by mihakralj** [comment]
All icons coming from Glyphicon set are impacted. I thought I transformed them all to an equivalent icons in Fontawesome set.
We can either hunt all outliers, or I can simply add back the Glyphicon set into the theme...

**Comment by mihakralj** [comment]
This one can be fixed with additional jquery line in `theme.js`:
`$('.fa-check-square-o').addClass('fa-check-square').removeClass('fa-check-square-o');`

The reason that Dracula has more issues is that it is missing the complete `theme.js`, not just specific injections that you don't need...

Add this into `theme.js` for Dracula:
```
$(document).ready(function() {

	$('.fa-check-square-o').addClass('fa-check-square').removeClass('fa-check-square-o');
	$('.fa-building-o').addClass('fa-microchip').removeClass('fa-building-o');
	$('.fa-map-signs').addClass('fa-network-wired').removeClass('fa-map-signs');
	$('.fa-map').addClass('fa-chart-network').removeClass('fa-map');
	$('.fa-expand').addClass('fa-network-wired').removeClass('fa-expand');
	$('.fa-lock').addClass('fa-shield-check').removeClass('fa-lock');
	$('.fa-clock-o').addClass('fa-clock').removeClass('fa-clocl-o');
	$('.fa-refresh').addClass('fa-redo').removeClass('fa-refresh');
	$('.glyphicon.glyphicon-fire').addClass('fa fa-route-highway').removeClass('glyphicon glyphicon-fire');
	$('.fa-support').addClass('fa fa-question-circle').removeClass('fa-support');
	$('.fa').addClass('fal fa-lg').removeClass('fa');
});
```

**Comment by rpoovey** [comment]
`$('.fa-check-square-o').addClass('fa-check-square').removeClass('fa-check-square-o');`
Corrected the enable with check box
&

`$('.fa-square-o').addClass('fa-square').removeClass('fa-square-o');`
Corrected the disable icon.

Added and corrected the issue. I'll keep an eye out for more missing icons.

**Comment by rpoovey** [comment]
I think I have hunted down all the missing icons in the Dracula theme. I'm gonna set this issue closed.
