### ISSUE TITLE
pkg: glib has a missing dependency: python37 

### ISSUE THREAD

**Issue by firestormo** [mimugmail/opn-repo#63]
After upgrading to 21.7 i see the same error about missing python37 dependency

https://forum.opnsense.org/index.php?topic=24144.0

**Comment by mimugmail** [comment]
Ah yes, now its time to build against 3.8

**Comment by madindehead** [comment]
Commenting here so I am alerted when the repo has been built against 3.8.

**Comment by mimugmail** [comment]
Currently I have build errors due to pkg, will take a bit

**Comment by mimugmail** [comment]
I updated it, just install all open updates
