### ISSUE TITLE
AdGuard Home Plugin Crashing..

### ISSUE THREAD

**Issue by motamedn** [mimugmail/opn-repo#64]
Firstly, great thanks for making the AGH plugin. I enabled SR-IOV in BIOS today but even after disabling it, it won't run..When I booted my OPNSense running in Hyper-V, the Adguard Home plugin crashes repeatedly. Cannot get it running. I can ping IPs but no DNS due to adguard crashing. I updated OPNSense to the latest and it still doesn't work. I am new to opening issues but if there is any information I can provide, let me know and I'll gladly provide it.

**Comment by motamedn** [comment]
I was able to get AGH up and running by uninstalling and reinstalling the plugin....but now all my settings and customizations are gone...
i have a checkpoint I could restore from before the uninstall/reinstall. Is there a file somewhere I can download from that checkpoint that has AGH settings?

**Comment by mimugmail** [comment]
No, settings are saved independently via its UI. Currently in vacation, better you ask at Reddit, there are many active users

**Comment by motamedn** [comment]
Thanks--Sorry about that I'll ask there!
