### ISSUE TITLE
Zeek failure on 21.7 -- python version needs updating to 3.8

### ISSUE THREAD

**Issue by zemsten** [mimugmail/opn-repo#66]
I figured I'd recount our conversation on reddit here for posterity's sake.

Zeek fails on install with the python errors:
```
  File "/usr/local/bin/zeekctl", line 17, in <module>
    from ZeekControl.zeekctl import ZeekCtl, ZeekControlError, CommandSyntaxError
  File "/usr/local/lib/zeek/python/zeekctl/ZeekControl/zeekctl.py", line 8, in <module>
    from ZeekControl import lock
  File "/usr/local/lib/zeek/python/zeekctl/ZeekControl/lock.py", line 4, in <module>
    from ZeekControl import config
  File "/usr/local/lib/zeek/python/zeekctl/ZeekControl/config.py", line 14, in <module>
    from .state import SqliteState
  File "/usr/local/lib/zeek/python/zeekctl/ZeekControl/state.py", line 2, in <module>
    import sqlite3
  File "/usr/local/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

It's looking for python3.7 instead of the new 3.8 version in 21.7.

**Comment by mimugmail** [comment]
Can you check if it works now? Just check for updates and install them

**Comment by zemsten** [comment]
Thanks for the update! Sorry for the delay, I generally only have time to tinker on weekends.

I updated and got Zeek installed without error, so it looks like your python update did the trick.

However, I still have a failure to start zeek. The in web UI it doesn't seem like the settings will save ever for some reason.

**Comment by zemsten** [comment]
> Thanks for the update! Sorry for the delay, I generally only have time to tinker on weekends.
> 
> I updated and got Zeek installed without error, so it looks like your python update did the trick.
> 
> However, I still have a failure to start zeek. The in web UI it doesn't seem like the settings will save ever for some reason.

It's reporting that Zeek is "misconfigured" still, but I just realized that It's looking for an SSL lib that it can't find, likely due to the fact that I'm running the LibreSSL flavor.
