### ISSUE TITLE
os-speedtest-community: Error when attempting to install Ookla module

### ISSUE THREAD

**Issue by Greelan** [mimugmail/opn-repo#67]
I recently reinstalled OPNsense as part of moving from UFS to ZFS, and as a result need to reinstall the speedtest plugin. I am running OPNsense 21.7.1 and os-speedtest-community 0.9_1.

I cannot now install the Ookla module. When attempting to do so I get the following in the logs for configd.py:

`Script action failed with Command '/bin/sh /usr/local/opnsense/scripts/OPNsense/speedtest/install_speedtest.sh socket' returned non-zero exit status 1. at Traceback (most recent call last): File "/usr/local/opnsense/service/modules/processhandler.py", line 478, in execute subprocess.check_call(script_command, env=self.config_environment, shell=True, File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '/bin/sh /usr/local/opnsense/scripts/OPNsense/speedtest/install_speedtest.sh socket' returned non-zero exit status 1.`

Be grateful for any suggestions.

**Comment by Greelan** [comment]
I suspect this is related to the move from python 3.7 to 3.8 in 21.7? I see there are some other issues that also appear related to that, and note mimugmail's comment that the repo is being rebuilt. I might try a manual install in the meantime

**Comment by Greelan** [comment]
Actually, manually running the script returns:

`pkg: https://bintray.com/ookla/download/download_file?file_path=ookla-speedtest-1.0.0-freebsd.pkg: Forbidden`

Going to that URL in a browser returns an error, on the basis that Bintray has been sunsetted from 1 May this year. Looks like the Ookla binary needs to be obtained from another source.

Ookla's website (https://www.speedtest.net/apps/cli) suggests the source should be:

`https://install.speedtest.net/app/cli/ookla-speedtest-1.0.0-freebsd.pkg`

**Comment by asche77** [comment]
On 21.7.1, neither installing the Speedtest nor the Ookla module (via GUI button) works for me.

**Comment by Greelan** [comment]
I suspect with the speedtest module it is because the package name is now `py38-speedtest-cli` with the shift to Python 3.8, rather than `py37-speedtest-cli` in the plugin script.

**Comment by asche77** [comment]
@Greelan , your suggestion for manual install works:
'sudo pkg add "https://install.speedtest.net/app/cli/ookla-speedtest-1.0.0-freebsd.pkg"'

**Comment by Greelan** [comment]
I know 😀

**Comment by mimugmail** [comment]
The repo is now updated, please give it a try

**Comment by Greelan** [comment]
Thanks. Do I need to reinstall the plugin to check? No update is showing when I check in the webgui. The glib package warning about the missing python37 dep is also still showing. Thanks

**Comment by mimugmail** [comment]
Please try again, stupid me :)

**Comment by Greelan** [comment]
Lol. Works now, and updated script appears to work fine too.
