### ISSUE TITLE
Samba package

### ISSUE THREAD

**Issue by nullpointerninja** [mimugmail/opn-repo#7]
Could it be possible to include samba as a plug-in?
Sharing a folder in the network is something many have requested over the years but including it in the base system would add possible security issues and bloat that would be unnecessary for most users. A plug-in could be the best solution.

**Comment by mimugmail** [comment]
Ok, it took me 2 hours to add more and more p5 dependencies. This is really a nightmare. 
When you install the 2 missing, the 2 new need 3 more. Insane.
If you have a complete list I can try again, but for now I have to stop this, sorry.

**Comment by mimugmail** [comment]
oh wait, maybe this was for smokeping :)

Can you try `pkg update && pkg install samba413`

**Comment by mimugmail** [comment]
samba doesn't start with HBSD packages .. maybe next try in a half year

**Comment by nullpointerninja** [comment]
Hi @mimugmail, now that 22.1 is using FreeBSD instead of HBSD, is there hope for this package?
