### ISSUE TITLE
Add description property to Adguardhome configd action

### ISSUE THREAD

**Issue by originaljay** [mimugmail/opn-repo#70]
First off, thank you for your plugin repository. I recently added the Adguardhome plugin to my OPNsense, and it is working great.
I've also set up the official ACME Client plugin and have it generating a Let's Encrypt certificate for my OPNsense host. I then set that certificate to be used for HTTPS with Adguardhome as well. The ACME Client plugin allows you to create "Automations" that run whenever a new certificate is issued. For instance, restarting the OPNsense webgui, so it starts using the new certificate immediately. I wanted to set an automation to restart the Adguardhome service for the same reason, but was disappointed to find it was not available in the list of plugin actions. After reviewing the OPNsense configd documentation (https://docs.opnsense.org/development/backend/configd.html?highlight=configd#action-properties) and checking the Adguardhome configd script (actions_adguardhome.conf), I found that simply adding the "description" field to the configd script ( and then restarting the configd service), made the Adguardhome "restart" action available in the OPNsense gui; both under the ACME Client plugin and also in the cron job commands list. The [restart] section of my actions_adguardhome.conf now looks like this:

> [restart]
command:/usr/local/etc/rc.d/adguardhome restart
parameters:
type:script
Message:restarting Adguardhome
description:Restart Adguardhome service

I was hoping you could add this into the plugin officially, so if it is ever updated or reinstalled, I won't have to make the same change. And hopefully other users of this plugin will find it similarly useful.

**Comment by mimugmail** [comment]
Sure, good idea :) I'll try to push an update this weekend

**Comment by originaljay** [comment]
> Sure, good idea :) I'll try to push an update this weekend

Thank you!

**Comment by mimugmail** [comment]
I just released the update which add this to cron.
