### ISSUE TITLE
Certificate verification failed

### ISSUE THREAD

**Issue by burntoc** [mimugmail/opn-repo#73]
Hey mmg, I know you're aware of this, but I wanted to see if you had fix options to recommend for those of us who are cert-process-challenged.  I changed my mirror to Cloudflare and it addressed the OPNsense repository cert issue, but this repo is still failing, preventing updates altogether.

Alternatively, is there a way to temporarily disable the repo at least long enough to install OPN updates (and wireguard-kmod again in my case) and then re-enable it without losing setup for things like AdGuardhome plugin?

**Comment by mimugmail** [comment]
Go on my website and search the folder where you fetched the conf, then remove the file and run pkg update

I will check the cert prob over the weekend

**Comment by burntoc** [comment]
Fair enough.  So just so I understand the processs and don't muck things up can you verify the following?
Step 1 - Go to /usr/local/etc/package/repos and delete mimugmail.conf
Step 2 - Do my OPN updates and wireguard-kmod reinstall
Step 3 - Run the fetch from your website again to re-pull the conf.
Step 4 - Reboot.

Sound right and my Adguardhome will retain the current config without requiring additional rework?

**Comment by mimugmail** [comment]
Can you replace recheck .. I dont get any errors

**Comment by AdMeik** [comment]
Hi Michael,

I have the same issue, remove the conf, remove the expired CA from System/Trust/Authorities, update OPNsense, re-add the Repository (with --no-verify-peer), but Repository Update still comes with:
`Updating mimugmail repository catalogue...
Certificate verification failed for /O=Digital Signature Trust Co./CN=DST Root CA X3
229124571136:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify`

The https://opn-repo.routerperformance.net looks okay, but OPNsense use old/cached? DST RootCA X3.
How to remove, or recheck, what you mean.

THX

**Comment by mimugmail** [comment]
System : Trust : Authorities and remove the old one?

**Comment by burntoc** [comment]
If the repo's cert is valid, no removal should be necessary, right?

**Comment by AdMeik** [comment]
![image](https://user-images.githubusercontent.com/34456047/135722833-37c7560b-f2c3-4609-99c3-39a471a91074.png)
Only this is configured.

**Comment by Smitimus** [comment]
I tried the above options, nothing seemed to work. I found this and compared what I had in the R3 Cert. It was close, but off in a few places. I replaced my R3 cert with the above, and it now works. Hope this helps. 

[https://forum.opnsense.org/index.php?topic=24950.msg119873#msg119873](https://forum.opnsense.org/index.php?topic=24950.msg119873#msg119873)

**Comment by burntoc** [comment]
Thanks for the update. I still don't understand why this would be necessary
if this repo generated a new, unexpired cert?

**Comment by Smitimus** [comment]
I am not a security professional... But the way I understand things the CA works as the first level of cert verification and is housed on the client side (which would be you opnsense box). In my case a new CA was present, but just had an inaccurate cert.

That said, I did not add the new CA to my box, and the date on it coresponds with an update I did. So, I am inclined to believe opnsense did this during an update. If so, opnsense sent the wrong CA cert to everyone.

**Comment by burntoc** [comment]
So it's basically a key with 2 parts. They send the public part to you, and
if it matches their private part then it will authenticate. When the cert
expired and it gots renewed, it should indicate a newer key and push the
public part so you can auth with the new private part. This should all
happen without you having to manually remove it, which is why we were able
to resolve with the OPNsense official repo without having to remove
anything, just an update.

**Comment by Smitimus** [comment]
Again, not a security pro.... But certs are 3 parts. Ca, public, and private. Yes everything SHOULD work automatically. But in my case the CA cert was off. The CA is stored in opnsense and not usually updated, likely for security/spoofing reasons.    I'm just sharing my experience and hoping it helps the community. Maybe not, who knows. 🤣

**Comment by burntoc** [comment]
That's weird that the CA required a manual updates. Even rarer, which is
why I didn't mention it, but yeah, that would do it.

**Comment by burntoc** [comment]
I got a reply that this repository has been moved to ZeroSSL to address the client-side CA and OPNsense config issues arising from this.  Thought I'd confirm that this has fixed the issue here, with no additional adjustments needed on my part.  As the CAs and certs are all valid now, the OPNsense update function completes properly again.
