### ISSUE TITLE
Slow Update and No Packages

### ISSUE THREAD

**Issue by liambresnahan** [mimugmail/opn-repo#77]
Hi All,

I'm running into an issue installing the repo - firstly, the install is very slow, even the fetch command seems to take a while, then the `pkg update` command takes a long time too. Once it is updated however I don't see any packages (either from the OPNsense repo or the community repo).

I'm running this from California, so thought perhaps it was my connection to Germany, but we're talking 20 plus seconds for the fetch and minutes for the update. Also when I curl the repo config from the router itself, all works quickly as expected...

Any thoughts?

**Comment by liambresnahan** [comment]
closing. Issue with DNS locally

**Comment by janwiesemann** [comment]
> closing. Issue with DNS locally

`It's always DNS`

I just ran into the same issue. If you haven't figured it our yet, it is caused by the unbound `Enable DNS64 Support` option.
