### ISSUE TITLE
[AdGuardHome] allow use of --no-etc-hosts  

### ISSUE THREAD

**Issue by spali** [mimugmail/opn-repo#84]
In April, AdGuardHome introduced new flag `--no-etc-hosts`. Sadly not configurable via config file.
https://github.com/AdguardTeam/AdGuardHome/commit/69f526b13d1f553dfcd3e3bad363c2ac148bef54

Would be great, if this could be added somehow.
Neatest solution would be to have a checkbox below "Enable" in the config GUI, but I would understand if you don't want to open this box ;)

In my case, AdGuardHome is returning IP's of all interfaces, independent of from where the query is coming from :(
This can lead to problems and also leaks internal ip's to networks on other interfaces.

**Comment by mimugmail** [comment]
What happens when you edit the file `/usr/local/etc/rc.d/adguardhome` on your system and add the option above here:
`command_args="-f -P /var/run/adguardhome.pid /usr/local/AdGuardHome/AdGuardHome -s run &"`

**Comment by mimugmail** [comment]
No worries :) 
Maybe just use portforward and dont use unbound at all?

**Comment by spali** [comment]
I use unbound (behind adguard) for internal domain only and forward remote site domains with overrides. Because bind plugin does not support the later and I wanted to keep internal domain separated from adguard.
But thanks anyway.
