### ISSUE TITLE
Plugin request : PiHole

### ISSUE THREAD

**Issue by tompointexe** [mimugmail/opn-repo#86]
Hi, any plan to make a pihole plugin so i could reperpose my unifi / pihole dedicated server ?
unless no freebsd version exist .. wich i think is the case ... so maybe not possible 👀 
Thanks

**Comment by mimugmail** [comment]
Why not using AdGuardHome plugin?

**Comment by tompointexe** [comment]
because i'm having specific lists for specific subnets, and to my knowlege, adguardhome cant do subnet based lists (correct me if i'm wrong 😅 )

**Comment by mimugmail** [comment]
I think you are wrong

**Comment by tompointexe** [comment]
Okey then, i'l try it then :)

**Comment by tompointexe** [comment]
Okey so looking into adguard, i can setup groups ... but i didn't find the setting to set specific lists to the created groups 👀

**Comment by mimugmail** [comment]
Isnt there an override when setting applications etc.?Currently not near a computer

**Comment by tompointexe** [comment]
Yes there is, but for apps only, not for lists (wants to add that having adguard web interface on 8080 blocks unifi controler to start / work )

**Comment by tompointexe** [comment]
While we are at it, any way to manualy update the unifi controller (installed using your repo) ?
