### ISSUE TITLE
Solarized Theme not in Plugins

### ISSUE THREAD

**Issue by reitermarkus** [mimugmail/opn-repo#88]
Hi,

I'm trying to install the `os-theme-solarized-community` plugin, but after adding and updating the repo, it doesn't show up in the “Plugins” tab. Some other plugins do show up in the list, however.

**Comment by mimugmail** [comment]
Are you on 22.1 Beta?

**Comment by reitermarkus** [comment]
Yes, I am on 22.1.r_3.

**Comment by mimugmail** [comment]
Please fetch again, updaed the repo

**Comment by reitermarkus** [comment]
Thanks, it is now showing up in Plugins. However, it seems to be broken. The CSS file (supposed to be at `/ui/themes/solarized/build/css/main.css?v=ceabdd952a8567a0` shows a 404.

**Comment by rpoovey** [comment]
@mimugmail I believe this is my fault. But I corrected this in PR #62 back in June 2021 which hasn't been merged yet.

**Comment by rpoovey** [comment]
@reitermarkus did you check for updates under "system - firmware - status"? This should then pull the file you need and update it correctly.

**Comment by reitermarkus** [comment]
Thanks, it's working now after the update.
