### ISSUE TITLE
geoipupdate package

### ISSUE THREAD

**Issue by onedr0p** [mimugmail/opn-repo#90]
Hi again! 👋

Thanks for adding rclone, I have one more request ☺️

It would be neat if you could package geoipupdate as well. It's a nice cli utility that's helpful in automating downloading the maxmind geoip databases.

- https://github.com/maxmind/geoipupdate

Thanks again!

**Comment by onedr0p** [comment]
viddy and croc would also be pretty neat to include :)

- https://github.com/sachaos/viddy
- https://github.com/schollz/croc

**Comment by mimugmail** [comment]
Tell me when you're finished, then I can add them all

**Comment by onedr0p** [comment]
That should be all for now, thanks haha

**Comment by mimugmail** [comment]
Are you really sure?? ;) Rien ne va plus ...

**Comment by mimugmail** [comment]
All in .. man viddy is cool 👍

**Comment by onedr0p** [comment]
It's one of my best finds of the year, I use it daily haha
