### ISSUE TITLE
Add Crowdsec plugin support

### ISSUE THREAD

**Issue by zemsten** [mimugmail/opn-repo#91]
Hey mimugmail!

This is a feature request.

I'm a fan of the crowdsec threat intel platform. They recently released a public beta of their package for OPNSense. I was thinking it'd be great if you had a few cycles to mirror it from their github repo into yours, that way we'd all have the opportunity to use it (even those who might be shy of the CLI).

Their repo is at https://github.com/crowdsecurity/opnsense-plugin-crowdsec should you be interested.

Close if not interested or worth it. Thanks!

**Comment by mimugmail** [comment]
I'm quite sure they will publish it theirselfs :) Just give them some time
