### ISSUE TITLE
Updated list and descriptions needed

### ISSUE THREAD

**Issue by thefunkygibbon** [mimugmail/opn-repo#98]
do not see zeek on my list of available plugins despite it being listed.  but then Home assistant is listed in my plugins and not mentioned on the github page.

maybe we could have some clarity as to what the plugins do?  ie is the home assistant something which allows HASS to manage /monitor the fw?  or is it actually HA running on the firewall? (not sure why you would want that though!)

**Comment by mimugmail** [comment]
Seems I forgot zeek, it will come the next days.
hass is for homeassistant so you can grab advance stats from it.

**Comment by mimugmail** [comment]
Zeek should be available now ...

**Comment by thefunkygibbon** [comment]
ok thanks.   i've installed the home assistant plugin.  I don't see any actual configuration aspects in the GUI.  is that right?  what is it supposed to connect to in HA?  I only see a pfsense integration within HACS but nothing in that or official for opnsense at all
