### ISSUE TITLE
REQUEST: Unifi Controller Beta Version Option

### ISSUE THREAD

**Issue by firestormo** [mimugmail/opn-repo#99]
@mihakralj can we get an option in the plugin to install the latest beta version of the controller as well, i have the stable version running on the opnsense box and working well now, but trying to migrate off of my old install on another device, the beta version of the controller. 

Or a field in the plugin to add the beta url.  also i see that the version of contoller here is old, as well.

https://community.ui.com/releases/UniFi-Network-Application-7-0-23/f1b404b4-f595-4346-aaa1-df6941e35525
I dont see a unix/ver with the source anymore.. maybe thats why as well. 

Thx

**Comment by mimugmail** [comment]
https://www.reddit.com/r/OPNsenseFirewall/comments/we7l7h/unifi7_plugin_finally_available/
